platform :ios, '13.4'
inhibit_all_warnings!

target 'NALS_Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NALS_Test
  pod 'Alamofire', '4.8.2'
  pod 'SDWebImage', '~> 5.0'
  pod 'SVProgressHUD'
  pod 'RealmSwift', '~> 10.22'
  
  end

  target 'NALS_TestTests' do
    inherit! :search_paths
    # Pods for testing
  end
