# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NALS_Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NALS_Test
  pod 'Alamofire', '~> 5.5'
  pod 'SDWebImage', '~> 5.0'


  target 'NALS_TestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NALS_TestUITests' do
    # Pods for testing
  end

end
