platform :ios, '13.4'
inhibit_all_warnings!

target 'Estrouge_Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Estrouge_Test
  pod 'Alamofire', '4.8.2'
  pod 'SDWebImage', '~> 5.0'
  pod 'SVProgressHUD'
  pod 'RealmSwift', '~> 10.22'
  
  end

  target 'Estrouge_TestTests' do
    use_frameworks!
    
    # Pods for testing
    pod 'OHHTTPStubs/Swift', '~> 9.1.0'
  end
